### ISSUE TITLE
Can't Compile with Rust 1.0.0-nightly

### ISSUE THREAD

**Issue by fribeiro1** [zslayton/stomp-rs#41]
I am getting the following error when compiling 0.3.6:

src\stomp.rs:3:12: 3:17 error: feature has been removed
src\stomp.rs:3 #![feature(phase)]
                          ^~~~~
error: aborting due to previous error
Could not compile `stomp`.

Please advise.

**Comment by zslayton** [comment]
Thank you for reporting this. As I mentioned in our conversation in #39, this is due to changes to the Rust language upstream. I'm planning to cut another release to catch up this weekend.

**Comment by fribeiro1** [comment]
Great, looking forward to play with it

**Comment by zslayton** [comment]
@fribeiro1 I've just released version 0.3.7 which aims to address this. Could you please verify that it compiles on your system?

**Comment by fribeiro1** [comment]
Fixed, thanks!
