### ISSUE TITLE
Add Support for Connection Headers

### ISSUE THREAD

**Issue by fribeiro1** [zslayton/stomp-rs#43]
Many use cases require connection headers, including, but not limited to, durable subscriptions in ActiveMQ.

**Comment by zslayton** [comment]
I've run into this myself. At the moment, I'm simply processing everything as a BytesMessage in Java, but obviously I'd like to give the developer the flexibility to choose whichever flavor of Message (s)he found to be most appropriate.

I'm still sketching out the best way to expose the ability to both add and suppress certain headers while keeping the API friendly. Unfortunately, Rust doesn't (yet?) support method overloading by parameter type, so it's not possible to make parameters optional very gracefully. At the moment, I already have:

* `connect`
* `connect_with_heartbeat`
* `connect_with_credentials`
* `connect_with_credentials_and_heartbeat`

as variations on the `connect` method. If I add another optional set of Headers, things will get even more complicated.

One possibility would be to add support an `on_before_connect(&mut Frame)` callback that allowed the developer to manipulate the Frame directly, but that feels like overkill.

**Comment by fribeiro1** [comment]
I am going to take a look at the Rust alternatives to method overloading myself, perhaps I can suggest a new design.

**Comment by zslayton** [comment]
Added in v0.6.0.
