### ISSUE TITLE
Add Support for Suppressing Content Length

### ISSUE THREAD

**Issue by fribeiro1** [zslayton/stomp-rs#45]
The suppression of the content-length header is used by ActiveMQ to differentiate binary and text messages [1], and should be supported.

[1] http://activemq.apache.org/stomp.html

**Comment by zslayton** [comment]
I've run into this myself. At the moment, I'm simply processing everything as a BytesMessage in Java, but obviously I'd like to give the developer the flexibility to choose whichever (s)he found more appropriate.

I'm still sketching out the best way to expose the ability to both add and suppress certain headers while keeping the API friendly. Unfortunately, Rust doesn't (yet?) support method overloading by parameter type, so it's not possible to make parameters optional. At the moment, I already have:

* `connect`
* `connect_with_heartbeat`
* `connect_with_credentials`
* `connect_with_credentials_and_heartbeat`

as variations on the `connect` method. If I add another optional set of Headers, things will get even more complicated.

One possibility would be to add support an `on_before_connect(&mut Frame)` callback that allowed the developer to manipulate the Frame directly, but that feels like overkill.

**Comment by zslayton** [comment]
I've run into this myself. At the moment, I'm simply processing everything as a BytesMessage in Java, but obviously I'd like to give the developer the flexibility to choose whichever flavor of Message (s)he found to be most appropriate.

In the short term, I can make `Sesion::send_bytes` and `Sesion::send_text` include and exclude the `content-length` header respectively. Down the road I'd like to make it possible to manipulate the headers of outbound messages at a more granular level.

I hope to make the `stomp` crate flexible enough that it can eventually be used as the groundwork for higher-level `activemq-stomp` and `rabbitmq-stomp` crates that contain all of the broker-specific features and code required to get the most out of the system.

**Comment by fribeiro1** [comment]
I have been porting a set of ActiveMQ samples to many languages and worked with many library developers, and found many times that the only way to avoid the ActiveMQ-specific flag is adding a alternative low-level API that allows users to manipulate the frames when they need to. You may want to consider the same approach here.

Note that I don't think users should need to go that far for #43 or #44, though.

**Comment by fribeiro1** [comment]
This is how my code looks like if I use the low-level API:

**Comment by zslayton** [comment]
It doesn't look too complicated! I suppose at some point I should make a Command enum with a SEND variant and the appropriate String implementation for complete type safety.

**Comment by fribeiro1** [comment]
Does body really need to be a vector, instead of a byte array?

**Comment by zslayton** [comment]
I missed your last comment somehow, sorry for the delay! I've opened #57 to look into whether `Frame.body` could be [u8]. I think that might help the performance of copying Frame structs.

For header suppression: I'm looking into making a 'builder' style API for some of the core functions of this library. See #54, #55 and #56 for rough sketches of what that might look like. I was thinking I might be able to allow header suppression by doing something like this:

```rust
session::message("/topics/penzance", "Modern major general")
  .with(header!("persistent", "true"))
  .with(SuppressedHeader("content-length"))
  .with(my_receipt_callback)
  .send();
```
This code follows the 'modifier' pattern that's used in [Iron](https://github.com/iron/iron) and made available in [rust-modifier](https://github.com/reem/rust-modifier).

**Comment by zslayton** [comment]
Added in v0.6.0.
