### ISSUE TITLE
Nack requeue false

### ISSUE THREAD

**Issue by frederikbosch** [zslayton/stomp-rs#91]
Sending a Nack frame with Rabbit MQ automatically enables [`requeue`](https://www.rabbitmq.com/stomp.html). If this is not desired behaviour, like in my case, then there is [no way to change it to false as default](https://groups.google.com/forum/#!msg/rabbitmq-users/Y8k0W3Oflto/bq0nkxrKq5QJ) on the server-side. So it must be implemented client-side.

The [STOMP spec is ambiguous on what the default setting should be](https://stomp.github.io/stomp-specification-1.2.html#NACK) and leaves it up to the server. It does even not specify the name of header that should be send if you do want control over the behaviour.

So with respect to the library, I would suggest adding a `on_frame` method to the `session` struct. This enables anyone to hack into the frame for these kind of situations: when the spec leaves it open how to implement something.

From the perspective of the user it then can look like this.

```rust
session.on_frame(|frame : &mut Frame| {
	match frame.command.as_ref() {
		"NACK" => {
			&frame.headers.push(Header::new("requeue", "false"));
		},
		_ => {}
	}
});
```

**Comment by zslayton** [comment]
Thanks for reporting this. I'd be open to adding callbacks for `on_before_send` and `on_before_receive` that each get the opportunity to manipulate `&mut Frame` before the main handlers are called. I wonder if the `AckOrNack` enum should have a third option to allow a custom frame to be specified.

Out of interest, in your situation could you simply respond with an `Ack` even though you encountered trouble processing the message? That way the server would drop the message rather than re-queuing it. Or are you relying on the `Nack` in other ways as well?

**Comment by frederikbosch** [comment]
@zslayton Interesting thought: to send an `Ack` even though the message fails. Actually, that would work in my case. However, I do think it is not the best solution. Probably the `Ack` would end up in the Rabbit MQ logs which indicates that the message was processed successfully (which is not the case).

Personally, I would be in favour of `on_before_send` and `on_before_receive`. That solves any case where the spec is not clear/leaves room for own implementation. A third option to the `AckOrNack` enum, would only help you in that particular case. I do not know the spec extremely well (I just chose STOMP because this package handles communication with Rabbit MQ best in my opinion.), so I cannot assess whether are many cases like that.

**Comment by zslayton** [comment]
I don't use RabbitMQ as often, but in ActiveMQ there aren't any records kept of the individual messages being handled (without enabling debug logging).

`on_before_send` and `on_before_receive` are certainly the most flexible approach. I'll plan on adding these.

**Comment by frederikbosch** [comment]
@zslayton Wonderful, I will see if I can those in with a PR. My Rust skills are [improving](https://github.com/genkgo/gworkerd).

**Comment by zslayton** [comment]
Great! This change is going to require a `FrameHandlerMut` variant of `FrameHandler`, which [currently lives in session.rs](https://github.com/zslayton/stomp-rs/blob/79bcc9e1333db9e7d69e8188abc48436bd3718e2/src/session.rs#L32-L50).

If present, the `on_before_receive` callback should be invoked [just before the `dispatch` method is](https://github.com/zslayton/stomp-rs/blob/79bcc9e1333db9e7d69e8188abc48436bd3718e2/src/session.rs#L126).

Similarly, `on_before_send` would be invoked in the `send` method [just before the write](https://github.com/zslayton/stomp-rs/blob/79bcc9e1333db9e7d69e8188abc48436bd3718e2/src/session.rs#L334).

**Comment by frederikbosch** [comment]
@zslayton Yes, I noticed that should be a new variant of FrameHandler. My first try failed miserably however. Storing closures with lifetimes etc are concepts that I am not used to.

**Comment by frederikbosch** [comment]
@zslayton But thanks for providing the right names and pointing into the right directions. That will help to create the correct solution.
